/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Users(
    val id: Long? = null,
    val email: String? = null,
    val password: String? = null,
    val nickname: String? = null,
    val provider: String? = null,
    val providerId: String? = null,
    val role: String? = null,
    val createdAt: OffsetDateTime? = null,
    val updatedAt: OffsetDateTime? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Users = other as Users
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.password == null) {
            if (o.password != null)
                return false
        }
        else if (this.password != o.password)
            return false
        if (this.nickname == null) {
            if (o.nickname != null)
                return false
        }
        else if (this.nickname != o.nickname)
            return false
        if (this.provider == null) {
            if (o.provider != null)
                return false
        }
        else if (this.provider != o.provider)
            return false
        if (this.providerId == null) {
            if (o.providerId != null)
                return false
        }
        else if (this.providerId != o.providerId)
            return false
        if (this.role == null) {
            if (o.role != null)
                return false
        }
        else if (this.role != o.role)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.password == null) 0 else this.password.hashCode())
        result = prime * result + (if (this.nickname == null) 0 else this.nickname.hashCode())
        result = prime * result + (if (this.provider == null) 0 else this.provider.hashCode())
        result = prime * result + (if (this.providerId == null) 0 else this.providerId.hashCode())
        result = prime * result + (if (this.role == null) 0 else this.role.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Users (")

        sb.append(id)
        sb.append(", ").append(email)
        sb.append(", ").append(password)
        sb.append(", ").append(nickname)
        sb.append(", ").append(provider)
        sb.append(", ").append(providerId)
        sb.append(", ").append(role)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
