@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.references


import com.nextmall.jooq.tables.AuthAccounts
import com.nextmall.jooq.tables.CheckoutLineItems
import com.nextmall.jooq.tables.CheckoutPaymentHandlers
import com.nextmall.jooq.tables.Checkouts
import com.nextmall.jooq.tables.Databasechangelog
import com.nextmall.jooq.tables.Databasechangeloglock
import com.nextmall.jooq.tables.Orders
import com.nextmall.jooq.tables.Products
import com.nextmall.jooq.tables.Users



/**
 * The table <code>public.auth_accounts</code>.
 */
val AUTH_ACCOUNTS: AuthAccounts = AuthAccounts.AUTH_ACCOUNTS

/**
 * The table <code>public.checkout_line_items</code>.
 */
val CHECKOUT_LINE_ITEMS: CheckoutLineItems = CheckoutLineItems.CHECKOUT_LINE_ITEMS

/**
 * The table <code>public.checkout_payment_handlers</code>.
 */
val CHECKOUT_PAYMENT_HANDLERS: CheckoutPaymentHandlers = CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS

/**
 * The table <code>public.checkouts</code>.
 */
val CHECKOUTS: Checkouts = Checkouts.CHECKOUTS

/**
 * The table <code>public.databasechangelog</code>.
 */
val DATABASECHANGELOG: Databasechangelog = Databasechangelog.DATABASECHANGELOG

/**
 * The table <code>public.databasechangeloglock</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>public.orders</code>.
 */
val ORDERS: Orders = Orders.ORDERS

/**
 * The table <code>public.products</code>.
 */
val PRODUCTS: Products = Products.PRODUCTS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
