@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.references


import com.nextmall.jooq.tables.AuthUserAccounts
import com.nextmall.jooq.tables.Databasechangelog
import com.nextmall.jooq.tables.Databasechangeloglock
import com.nextmall.jooq.tables.Users



/**
 * The table <code>public.auth_user_accounts</code>.
 */
val AUTH_USER_ACCOUNTS: AuthUserAccounts = AuthUserAccounts.AUTH_USER_ACCOUNTS

/**
 * The table <code>public.databasechangelog</code>.
 */
val DATABASECHANGELOG: Databasechangelog = Databasechangelog.DATABASECHANGELOG

/**
 * The table <code>public.databasechangeloglock</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
