@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.references


import com.nextmall.jooq.tables.AuthAccounts
import com.nextmall.jooq.tables.Databasechangelog
import com.nextmall.jooq.tables.Databasechangeloglock
import com.nextmall.jooq.tables.Users



/**
 * The table <code>public.auth_accounts</code>.
 */
val AUTH_ACCOUNTS: AuthAccounts = AuthAccounts.AUTH_ACCOUNTS

/**
 * The table <code>public.databasechangelog</code>.
 */
val DATABASECHANGELOG: Databasechangelog = Databasechangelog.DATABASECHANGELOG

/**
 * The table <code>public.databasechangeloglock</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
