/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.AuthUserAccounts

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AuthUserAccountsRecord() : UpdatableRecordImpl<AuthUserAccountsRecord>(AuthUserAccounts.AUTH_USER_ACCOUNTS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var userId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var provider: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var providerAccountId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var passwordHash: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised AuthUserAccountsRecord
     */
    constructor(id: Long? = null, userId: Long? = null, provider: String? = null, providerAccountId: String? = null, passwordHash: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.userId = userId
        this.provider = provider
        this.providerAccountId = providerAccountId
        this.passwordHash = passwordHash
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
