/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.CheckoutPaymentHandlers

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CheckoutPaymentHandlersRecord() : UpdatableRecordImpl<CheckoutPaymentHandlersRecord>(CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var checkoutId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var handlerType: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var handlerProvider: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var sortOrder: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised CheckoutPaymentHandlersRecord
     */
    constructor(id: Long? = null, checkoutId: String? = null, handlerType: String? = null, handlerProvider: String? = null, sortOrder: Int? = null): this() {
        this.id = id
        this.checkoutId = checkoutId
        this.handlerType = handlerType
        this.handlerProvider = handlerProvider
        this.sortOrder = sortOrder
        resetTouchedOnNotNull()
    }
}
