/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.CheckoutLineItems

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CheckoutLineItemsRecord() : UpdatableRecordImpl<CheckoutLineItemsRecord>(CheckoutLineItems.CHECKOUT_LINE_ITEMS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var checkoutId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var lineItemId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var title: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var quantity: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var priceAmount: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    open var priceCurrency: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var imageUrl: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised CheckoutLineItemsRecord
     */
    constructor(id: Long? = null, checkoutId: String? = null, lineItemId: String? = null, title: String? = null, quantity: Int? = null, priceAmount: Long? = null, priceCurrency: String? = null, imageUrl: String? = null): this() {
        this.id = id
        this.checkoutId = checkoutId
        this.lineItemId = lineItemId
        this.title = title
        this.quantity = quantity
        this.priceAmount = priceAmount
        this.priceCurrency = priceCurrency
        this.imageUrl = imageUrl
        resetTouchedOnNotNull()
    }
}
