/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.Checkouts

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CheckoutsRecord() : UpdatableRecordImpl<CheckoutsRecord>(Checkouts.CHECKOUTS) {

    open var checkoutId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var status: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var currency: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var buyerId: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var buyerEmail: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var buyerName: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var shippingLine1: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var shippingLine2: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var shippingCity: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var shippingRegion: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var shippingPostalCode: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var shippingCountry: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var billingLine1: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var billingLine2: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var billingCity: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var billingRegion: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var billingPostalCode: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var billingCountry: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var subtotalAmount: Long?
        set(value): Unit = set(18, value)
        get(): Long? = get(18) as Long?

    open var taxAmount: Long?
        set(value): Unit = set(19, value)
        get(): Long? = get(19) as Long?

    open var shippingAmount: Long?
        set(value): Unit = set(20, value)
        get(): Long? = get(20) as Long?

    open var discountAmount: Long?
        set(value): Unit = set(21, value)
        get(): Long? = get(21) as Long?

    open var totalAmount: Long?
        set(value): Unit = set(22, value)
        get(): Long? = get(22) as Long?

    open var termsUrl: String?
        set(value): Unit = set(23, value)
        get(): String? = get(23) as String?

    open var privacyUrl: String?
        set(value): Unit = set(24, value)
        get(): String? = get(24) as String?

    open var refundUrl: String?
        set(value): Unit = set(25, value)
        get(): String? = get(25) as String?

    open var expiresAt: OffsetDateTime?
        set(value): Unit = set(26, value)
        get(): OffsetDateTime? = get(26) as OffsetDateTime?

    open var paymentType: String?
        set(value): Unit = set(27, value)
        get(): String? = get(27) as String?

    open var paymentProvider: String?
        set(value): Unit = set(28, value)
        get(): String? = get(28) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(29, value)
        get(): OffsetDateTime? = get(29) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(30, value)
        get(): OffsetDateTime? = get(30) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised CheckoutsRecord
     */
    constructor(checkoutId: String? = null, status: String? = null, currency: String? = null, buyerId: String? = null, buyerEmail: String? = null, buyerName: String? = null, shippingLine1: String? = null, shippingLine2: String? = null, shippingCity: String? = null, shippingRegion: String? = null, shippingPostalCode: String? = null, shippingCountry: String? = null, billingLine1: String? = null, billingLine2: String? = null, billingCity: String? = null, billingRegion: String? = null, billingPostalCode: String? = null, billingCountry: String? = null, subtotalAmount: Long? = null, taxAmount: Long? = null, shippingAmount: Long? = null, discountAmount: Long? = null, totalAmount: Long? = null, termsUrl: String? = null, privacyUrl: String? = null, refundUrl: String? = null, expiresAt: OffsetDateTime? = null, paymentType: String? = null, paymentProvider: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.checkoutId = checkoutId
        this.status = status
        this.currency = currency
        this.buyerId = buyerId
        this.buyerEmail = buyerEmail
        this.buyerName = buyerName
        this.shippingLine1 = shippingLine1
        this.shippingLine2 = shippingLine2
        this.shippingCity = shippingCity
        this.shippingRegion = shippingRegion
        this.shippingPostalCode = shippingPostalCode
        this.shippingCountry = shippingCountry
        this.billingLine1 = billingLine1
        this.billingLine2 = billingLine2
        this.billingCity = billingCity
        this.billingRegion = billingRegion
        this.billingPostalCode = billingPostalCode
        this.billingCountry = billingCountry
        this.subtotalAmount = subtotalAmount
        this.taxAmount = taxAmount
        this.shippingAmount = shippingAmount
        this.discountAmount = discountAmount
        this.totalAmount = totalAmount
        this.termsUrl = termsUrl
        this.privacyUrl = privacyUrl
        this.refundUrl = refundUrl
        this.expiresAt = expiresAt
        this.paymentType = paymentType
        this.paymentProvider = paymentProvider
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
