/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.Orders

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class OrdersRecord() : UpdatableRecordImpl<OrdersRecord>(Orders.ORDERS) {

    open var orderId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var userId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var productId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var quantity: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var totalPrice: BigDecimal?
        set(value): Unit = set(4, value)
        get(): BigDecimal? = get(4) as BigDecimal?

    open var status: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised OrdersRecord
     */
    constructor(orderId: Long? = null, userId: Long? = null, productId: Long? = null, quantity: Int? = null, totalPrice: BigDecimal? = null, status: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.orderId = orderId
        this.userId = userId
        this.productId = productId
        this.quantity = quantity
        this.totalPrice = totalPrice
        this.status = status
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
