/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.Orders

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class OrdersRecord() : UpdatableRecordImpl<OrdersRecord>(Orders.ORDERS) {

    open var orderId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var checkoutId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var currency: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var permalinkUrl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var lineItemsJson: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var totalsJson: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var fulfillmentJson: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var adjustmentsJson: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised OrdersRecord
     */
    constructor(orderId: Long? = null, checkoutId: String? = null, currency: String? = null, permalinkUrl: String? = null, lineItemsJson: String? = null, totalsJson: String? = null, fulfillmentJson: String? = null, adjustmentsJson: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.orderId = orderId
        this.checkoutId = checkoutId
        this.currency = currency
        this.permalinkUrl = permalinkUrl
        this.lineItemsJson = lineItemsJson
        this.totalsJson = totalsJson
        this.fulfillmentJson = fulfillmentJson
        this.adjustmentsJson = adjustmentsJson
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
