/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.Products

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ProductsRecord() : UpdatableRecordImpl<ProductsRecord>(Products.PRODUCTS) {

    open var productId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var price: BigDecimal?
        set(value): Unit = set(2, value)
        get(): BigDecimal? = get(2) as BigDecimal?

    open var stock: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var sellerId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var category: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ProductsRecord
     */
    constructor(productId: Long? = null, name: String? = null, price: BigDecimal? = null, stock: Int? = null, sellerId: Long? = null, category: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.productId = productId
        this.name = name
        this.price = price
        this.stock = stock
        this.sellerId = sellerId
        this.category = category
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
