/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables.records


import com.nextmall.jooq.tables.Users

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var email: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var nickname: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var status: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Long? = null, email: String? = null, nickname: String? = null, status: String? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.email = email
        this.nickname = nickname
        this.status = status
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
