/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq


import com.nextmall.jooq.tables.AuthAccounts
import com.nextmall.jooq.tables.CheckoutLineItems
import com.nextmall.jooq.tables.CheckoutPaymentHandlers
import com.nextmall.jooq.tables.Checkouts
import com.nextmall.jooq.tables.Databasechangelog
import com.nextmall.jooq.tables.Databasechangeloglock
import com.nextmall.jooq.tables.Orders
import com.nextmall.jooq.tables.Products
import com.nextmall.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.auth_accounts</code>.
     */
    val AUTH_ACCOUNTS: AuthAccounts get() = AuthAccounts.AUTH_ACCOUNTS

    /**
     * The table <code>public.checkout_line_items</code>.
     */
    val CHECKOUT_LINE_ITEMS: CheckoutLineItems get() = CheckoutLineItems.CHECKOUT_LINE_ITEMS

    /**
     * The table <code>public.checkout_payment_handlers</code>.
     */
    val CHECKOUT_PAYMENT_HANDLERS: CheckoutPaymentHandlers get() = CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS

    /**
     * The table <code>public.checkouts</code>.
     */
    val CHECKOUTS: Checkouts get() = Checkouts.CHECKOUTS

    /**
     * The table <code>public.databasechangelog</code>.
     */
    val DATABASECHANGELOG: Databasechangelog get() = Databasechangelog.DATABASECHANGELOG

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    val DATABASECHANGELOGLOCK: Databasechangeloglock get() = Databasechangeloglock.DATABASECHANGELOGLOCK

    /**
     * The table <code>public.orders</code>.
     */
    val ORDERS: Orders get() = Orders.ORDERS

    /**
     * The table <code>public.products</code>.
     */
    val PRODUCTS: Products get() = Products.PRODUCTS

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AuthAccounts.AUTH_ACCOUNTS,
        CheckoutLineItems.CHECKOUT_LINE_ITEMS,
        CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS,
        Checkouts.CHECKOUTS,
        Databasechangelog.DATABASECHANGELOG,
        Databasechangeloglock.DATABASECHANGELOGLOCK,
        Orders.ORDERS,
        Products.PRODUCTS,
        Users.USERS
    )
}
