@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.keys


import com.nextmall.jooq.tables.AuthAccounts
import com.nextmall.jooq.tables.Databasechangeloglock
import com.nextmall.jooq.tables.Users
import com.nextmall.jooq.tables.records.AuthAccountsRecord
import com.nextmall.jooq.tables.records.DatabasechangeloglockRecord
import com.nextmall.jooq.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val AUTH_ACCOUNTS_PKEY: UniqueKey<AuthAccountsRecord> = Internal.createUniqueKey(AuthAccounts.AUTH_ACCOUNTS, DSL.name("auth_accounts_pkey"), arrayOf(AuthAccounts.AUTH_ACCOUNTS.ID), true)
val UK_AUTH_ACCOUNTS_PROVIDER_ACCOUNT_ID: UniqueKey<AuthAccountsRecord> = Internal.createUniqueKey(AuthAccounts.AUTH_ACCOUNTS, DSL.name("uk_auth_accounts_provider_account_id"), arrayOf(AuthAccounts.AUTH_ACCOUNTS.PROVIDER, AuthAccounts.AUTH_ACCOUNTS.PROVIDER_ACCOUNT_ID), true)
val DATABASECHANGELOGLOCK_PKEY: UniqueKey<DatabasechangeloglockRecord> = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), arrayOf(Databasechangeloglock.DATABASECHANGELOGLOCK.ID), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val AUTH_ACCOUNTS__FK_AUTH_ACCOUNTS_USER_ID: ForeignKey<AuthAccountsRecord, UsersRecord> = Internal.createForeignKey(AuthAccounts.AUTH_ACCOUNTS, DSL.name("fk_auth_accounts_user_id"), arrayOf(AuthAccounts.AUTH_ACCOUNTS.USER_ID), com.nextmall.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
