@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.indexes


import com.nextmall.jooq.tables.Users

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_USERS_EMAIL: Index = Internal.createIndex(DSL.name("idx_users_email"), Users.USERS, arrayOf(Users.USERS.EMAIL), false)
