@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.indexes


import com.nextmall.jooq.tables.CheckoutLineItems
import com.nextmall.jooq.tables.CheckoutPaymentHandlers
import com.nextmall.jooq.tables.Orders
import com.nextmall.jooq.tables.Products

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_CHECKOUT_LINE_ITEMS_CHECKOUT_ID: Index = Internal.createIndex(DSL.name("idx_checkout_line_items_checkout_id"), CheckoutLineItems.CHECKOUT_LINE_ITEMS, arrayOf(CheckoutLineItems.CHECKOUT_LINE_ITEMS.CHECKOUT_ID), false)
val IDX_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT_ID: Index = Internal.createIndex(DSL.name("idx_checkout_payment_handlers_checkout_id"), CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS, arrayOf(CheckoutPaymentHandlers.CHECKOUT_PAYMENT_HANDLERS.CHECKOUT_ID), false)
val IDX_ORDERS_CHECKOUT_ID: Index = Internal.createIndex(DSL.name("idx_orders_checkout_id"), Orders.ORDERS, arrayOf(Orders.ORDERS.CHECKOUT_ID), false)
val IDX_PRODUCTS_SELLER_ID: Index = Internal.createIndex(DSL.name("idx_products_seller_id"), Products.PRODUCTS, arrayOf(Products.PRODUCTS.SELLER_ID), false)
