/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.keys.AUTH_ACCOUNTS_PKEY
import com.nextmall.jooq.keys.UK_AUTH_ACCOUNTS_PROVIDER_ACCOUNT_ID
import com.nextmall.jooq.tables.records.AuthAccountsRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AuthAccounts(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuthAccountsRecord>?,
    parentPath: InverseForeignKey<out Record, AuthAccountsRecord>?,
    aliased: Table<AuthAccountsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuthAccountsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.auth_accounts</code>
         */
        val AUTH_ACCOUNTS: AuthAccounts = AuthAccounts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthAccountsRecord> = AuthAccountsRecord::class.java

    /**
     * The column <code>public.auth_accounts.id</code>.
     */
    val ID: TableField<AuthAccountsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.auth_accounts.user_id</code>.
     */
    val USER_ID: TableField<AuthAccountsRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.auth_accounts.provider</code>.
     */
    val PROVIDER: TableField<AuthAccountsRecord, String?> = createField(DSL.name("provider"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.auth_accounts.provider_account_id</code>.
     */
    val PROVIDER_ACCOUNT_ID: TableField<AuthAccountsRecord, String?> = createField(DSL.name("provider_account_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.auth_accounts.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<AuthAccountsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.auth_accounts.status</code>.
     */
    val STATUS: TableField<AuthAccountsRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.auth_accounts.created_at</code>.
     */
    val CREATED_AT: TableField<AuthAccountsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.auth_accounts.updated_at</code>.
     */
    val UPDATED_AT: TableField<AuthAccountsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<AuthAccountsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuthAccountsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuthAccountsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.auth_accounts</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.auth_accounts</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.auth_accounts</code> table reference
     */
    constructor(): this(DSL.name("auth_accounts"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthAccountsRecord> = AUTH_ACCOUNTS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AuthAccountsRecord>> = listOf(UK_AUTH_ACCOUNTS_PROVIDER_ACCOUNT_ID)
    override fun `as`(alias: String): AuthAccounts = AuthAccounts(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthAccounts = AuthAccounts(alias, this)
    override fun `as`(alias: Table<*>): AuthAccounts = AuthAccounts(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthAccounts = AuthAccounts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthAccounts = AuthAccounts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthAccounts = AuthAccounts(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AuthAccounts = AuthAccounts(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AuthAccounts = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AuthAccounts = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AuthAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AuthAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AuthAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AuthAccounts = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AuthAccounts = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AuthAccounts = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AuthAccounts = where(DSL.notExists(select))
}
