/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.keys.AUTH_USER_ACCOUNTS_PKEY
import com.nextmall.jooq.keys.AUTH_USER_ACCOUNTS__FK_AUTH_USER_ACCOUNTS_USER_ID
import com.nextmall.jooq.keys.UK_AUTH_USER_ACCOUNTS_PROVIDER_ACCOUNT_ID
import com.nextmall.jooq.tables.Users.UsersPath
import com.nextmall.jooq.tables.records.AuthUserAccountsRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AuthUserAccounts(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuthUserAccountsRecord>?,
    parentPath: InverseForeignKey<out Record, AuthUserAccountsRecord>?,
    aliased: Table<AuthUserAccountsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuthUserAccountsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.auth_user_accounts</code>
         */
        val AUTH_USER_ACCOUNTS: AuthUserAccounts = AuthUserAccounts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthUserAccountsRecord> = AuthUserAccountsRecord::class.java

    /**
     * The column <code>public.auth_user_accounts.id</code>.
     */
    val ID: TableField<AuthUserAccountsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.auth_user_accounts.user_id</code>.
     */
    val USER_ID: TableField<AuthUserAccountsRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.auth_user_accounts.provider</code>.
     */
    val PROVIDER: TableField<AuthUserAccountsRecord, String?> = createField(DSL.name("provider"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.auth_user_accounts.provider_account_id</code>.
     */
    val PROVIDER_ACCOUNT_ID: TableField<AuthUserAccountsRecord, String?> = createField(DSL.name("provider_account_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.auth_user_accounts.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<AuthUserAccountsRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.auth_user_accounts.created_at</code>.
     */
    val CREATED_AT: TableField<AuthUserAccountsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.auth_user_accounts.updated_at</code>.
     */
    val UPDATED_AT: TableField<AuthUserAccountsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<AuthUserAccountsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuthUserAccountsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuthUserAccountsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.auth_user_accounts</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.auth_user_accounts</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.auth_user_accounts</code> table reference
     */
    constructor(): this(DSL.name("auth_user_accounts"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthUserAccountsRecord>?, parentPath: InverseForeignKey<out Record, AuthUserAccountsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AUTH_USER_ACCOUNTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AuthUserAccountsPath : AuthUserAccounts, Path<AuthUserAccountsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthUserAccountsRecord>?, parentPath: InverseForeignKey<out Record, AuthUserAccountsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AuthUserAccountsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AuthUserAccountsPath = AuthUserAccountsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AuthUserAccountsPath = AuthUserAccountsPath(alias, this)
        override fun `as`(alias: Table<*>): AuthUserAccountsPath = AuthUserAccountsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthUserAccountsRecord> = AUTH_USER_ACCOUNTS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AuthUserAccountsRecord>> = listOf(UK_AUTH_USER_ACCOUNTS_PROVIDER_ACCOUNT_ID)
    override fun getReferences(): List<ForeignKey<AuthUserAccountsRecord, *>> = listOf(AUTH_USER_ACCOUNTS__FK_AUTH_USER_ACCOUNTS_USER_ID)

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, AUTH_USER_ACCOUNTS__FK_AUTH_USER_ACCOUNTS_USER_ID, null) }
    override fun `as`(alias: String): AuthUserAccounts = AuthUserAccounts(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthUserAccounts = AuthUserAccounts(alias, this)
    override fun `as`(alias: Table<*>): AuthUserAccounts = AuthUserAccounts(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthUserAccounts = AuthUserAccounts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthUserAccounts = AuthUserAccounts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthUserAccounts = AuthUserAccounts(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AuthUserAccounts = AuthUserAccounts(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AuthUserAccounts = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AuthUserAccounts = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AuthUserAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AuthUserAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AuthUserAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AuthUserAccounts = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AuthUserAccounts = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AuthUserAccounts = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AuthUserAccounts = where(DSL.notExists(select))
}
