/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.indexes.IDX_CHECKOUT_LINE_ITEMS_CHECKOUT_ID
import com.nextmall.jooq.keys.CHECKOUT_LINE_ITEMS_PKEY
import com.nextmall.jooq.keys.CHECKOUT_LINE_ITEMS__FK_CHECKOUT_LINE_ITEMS_CHECKOUT
import com.nextmall.jooq.tables.Checkouts.CheckoutsPath
import com.nextmall.jooq.tables.records.CheckoutLineItemsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CheckoutLineItems(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CheckoutLineItemsRecord>?,
    parentPath: InverseForeignKey<out Record, CheckoutLineItemsRecord>?,
    aliased: Table<CheckoutLineItemsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CheckoutLineItemsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.checkout_line_items</code>
         */
        val CHECKOUT_LINE_ITEMS: CheckoutLineItems = CheckoutLineItems()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CheckoutLineItemsRecord> = CheckoutLineItemsRecord::class.java

    /**
     * The column <code>public.checkout_line_items.id</code>.
     */
    val ID: TableField<CheckoutLineItemsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.checkout_id</code>.
     */
    val CHECKOUT_ID: TableField<CheckoutLineItemsRecord, String?> = createField(DSL.name("checkout_id"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.line_item_id</code>.
     */
    val LINE_ITEM_ID: TableField<CheckoutLineItemsRecord, String?> = createField(DSL.name("line_item_id"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.title</code>.
     */
    val TITLE: TableField<CheckoutLineItemsRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.quantity</code>.
     */
    val QUANTITY: TableField<CheckoutLineItemsRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.price_amount</code>.
     */
    val PRICE_AMOUNT: TableField<CheckoutLineItemsRecord, Long?> = createField(DSL.name("price_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.price_currency</code>.
     */
    val PRICE_CURRENCY: TableField<CheckoutLineItemsRecord, String?> = createField(DSL.name("price_currency"), SQLDataType.VARCHAR(3).nullable(false), this, "")

    /**
     * The column <code>public.checkout_line_items.image_url</code>.
     */
    val IMAGE_URL: TableField<CheckoutLineItemsRecord, String?> = createField(DSL.name("image_url"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<CheckoutLineItemsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CheckoutLineItemsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CheckoutLineItemsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.checkout_line_items</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.checkout_line_items</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.checkout_line_items</code> table reference
     */
    constructor(): this(DSL.name("checkout_line_items"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutLineItemsRecord>?, parentPath: InverseForeignKey<out Record, CheckoutLineItemsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CHECKOUT_LINE_ITEMS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CheckoutLineItemsPath : CheckoutLineItems, Path<CheckoutLineItemsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutLineItemsRecord>?, parentPath: InverseForeignKey<out Record, CheckoutLineItemsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CheckoutLineItemsRecord>): super(alias, aliased)
        override fun `as`(alias: String): CheckoutLineItemsPath = CheckoutLineItemsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CheckoutLineItemsPath = CheckoutLineItemsPath(alias, this)
        override fun `as`(alias: Table<*>): CheckoutLineItemsPath = CheckoutLineItemsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_CHECKOUT_LINE_ITEMS_CHECKOUT_ID)
    override fun getPrimaryKey(): UniqueKey<CheckoutLineItemsRecord> = CHECKOUT_LINE_ITEMS_PKEY
    override fun getReferences(): List<ForeignKey<CheckoutLineItemsRecord, *>> = listOf(CHECKOUT_LINE_ITEMS__FK_CHECKOUT_LINE_ITEMS_CHECKOUT)

    /**
     * Get the implicit join path to the <code>public.checkouts</code> table.
     */
    fun checkouts(): CheckoutsPath = checkouts
    val checkouts: CheckoutsPath by lazy { CheckoutsPath(this, CHECKOUT_LINE_ITEMS__FK_CHECKOUT_LINE_ITEMS_CHECKOUT, null) }
    override fun `as`(alias: String): CheckoutLineItems = CheckoutLineItems(DSL.name(alias), this)
    override fun `as`(alias: Name): CheckoutLineItems = CheckoutLineItems(alias, this)
    override fun `as`(alias: Table<*>): CheckoutLineItems = CheckoutLineItems(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CheckoutLineItems = CheckoutLineItems(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CheckoutLineItems = CheckoutLineItems(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CheckoutLineItems = CheckoutLineItems(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CheckoutLineItems = CheckoutLineItems(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CheckoutLineItems = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CheckoutLineItems = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CheckoutLineItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CheckoutLineItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CheckoutLineItems = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CheckoutLineItems = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CheckoutLineItems = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CheckoutLineItems = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CheckoutLineItems = where(DSL.notExists(select))
}
