/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.keys.CHECKOUTS_PKEY
import com.nextmall.jooq.keys.CHECKOUT_LINE_ITEMS__FK_CHECKOUT_LINE_ITEMS_CHECKOUT
import com.nextmall.jooq.keys.CHECKOUT_PAYMENT_HANDLERS__FK_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT
import com.nextmall.jooq.tables.CheckoutLineItems.CheckoutLineItemsPath
import com.nextmall.jooq.tables.CheckoutPaymentHandlers.CheckoutPaymentHandlersPath
import com.nextmall.jooq.tables.records.CheckoutsRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Checkouts(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CheckoutsRecord>?,
    parentPath: InverseForeignKey<out Record, CheckoutsRecord>?,
    aliased: Table<CheckoutsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CheckoutsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.checkouts</code>
         */
        val CHECKOUTS: Checkouts = Checkouts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CheckoutsRecord> = CheckoutsRecord::class.java

    /**
     * The column <code>public.checkouts.checkout_id</code>.
     */
    val CHECKOUT_ID: TableField<CheckoutsRecord, String?> = createField(DSL.name("checkout_id"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.checkouts.status</code>.
     */
    val STATUS: TableField<CheckoutsRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column <code>public.checkouts.currency</code>.
     */
    val CURRENCY: TableField<CheckoutsRecord, String?> = createField(DSL.name("currency"), SQLDataType.VARCHAR(3).nullable(false), this, "")

    /**
     * The column <code>public.checkouts.buyer_id</code>.
     */
    val BUYER_ID: TableField<CheckoutsRecord, String?> = createField(DSL.name("buyer_id"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.checkouts.buyer_email</code>.
     */
    val BUYER_EMAIL: TableField<CheckoutsRecord, String?> = createField(DSL.name("buyer_email"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.buyer_name</code>.
     */
    val BUYER_NAME: TableField<CheckoutsRecord, String?> = createField(DSL.name("buyer_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.shipping_line1</code>.
     */
    val SHIPPING_LINE1: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_line1"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.shipping_line2</code>.
     */
    val SHIPPING_LINE2: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_line2"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.shipping_city</code>.
     */
    val SHIPPING_CITY: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_city"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checkouts.shipping_region</code>.
     */
    val SHIPPING_REGION: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_region"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checkouts.shipping_postal_code</code>.
     */
    val SHIPPING_POSTAL_CODE: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_postal_code"), SQLDataType.VARCHAR(32), this, "")

    /**
     * The column <code>public.checkouts.shipping_country</code>.
     */
    val SHIPPING_COUNTRY: TableField<CheckoutsRecord, String?> = createField(DSL.name("shipping_country"), SQLDataType.VARCHAR(2), this, "")

    /**
     * The column <code>public.checkouts.billing_line1</code>.
     */
    val BILLING_LINE1: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_line1"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.billing_line2</code>.
     */
    val BILLING_LINE2: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_line2"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.checkouts.billing_city</code>.
     */
    val BILLING_CITY: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_city"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checkouts.billing_region</code>.
     */
    val BILLING_REGION: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_region"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checkouts.billing_postal_code</code>.
     */
    val BILLING_POSTAL_CODE: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_postal_code"), SQLDataType.VARCHAR(32), this, "")

    /**
     * The column <code>public.checkouts.billing_country</code>.
     */
    val BILLING_COUNTRY: TableField<CheckoutsRecord, String?> = createField(DSL.name("billing_country"), SQLDataType.VARCHAR(2), this, "")

    /**
     * The column <code>public.checkouts.subtotal_amount</code>.
     */
    val SUBTOTAL_AMOUNT: TableField<CheckoutsRecord, Long?> = createField(DSL.name("subtotal_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkouts.tax_amount</code>.
     */
    val TAX_AMOUNT: TableField<CheckoutsRecord, Long?> = createField(DSL.name("tax_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkouts.shipping_amount</code>.
     */
    val SHIPPING_AMOUNT: TableField<CheckoutsRecord, Long?> = createField(DSL.name("shipping_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkouts.discount_amount</code>.
     */
    val DISCOUNT_AMOUNT: TableField<CheckoutsRecord, Long?> = createField(DSL.name("discount_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkouts.total_amount</code>.
     */
    val TOTAL_AMOUNT: TableField<CheckoutsRecord, Long?> = createField(DSL.name("total_amount"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkouts.terms_url</code>.
     */
    val TERMS_URL: TableField<CheckoutsRecord, String?> = createField(DSL.name("terms_url"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.checkouts.privacy_url</code>.
     */
    val PRIVACY_URL: TableField<CheckoutsRecord, String?> = createField(DSL.name("privacy_url"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.checkouts.refund_url</code>.
     */
    val REFUND_URL: TableField<CheckoutsRecord, String?> = createField(DSL.name("refund_url"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.checkouts.expires_at</code>.
     */
    val EXPIRES_AT: TableField<CheckoutsRecord, OffsetDateTime?> = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.checkouts.payment_type</code>.
     */
    val PAYMENT_TYPE: TableField<CheckoutsRecord, String?> = createField(DSL.name("payment_type"), SQLDataType.VARCHAR(32), this, "")

    /**
     * The column <code>public.checkouts.payment_provider</code>.
     */
    val PAYMENT_PROVIDER: TableField<CheckoutsRecord, String?> = createField(DSL.name("payment_provider"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.checkouts.created_at</code>.
     */
    val CREATED_AT: TableField<CheckoutsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.checkouts.updated_at</code>.
     */
    val UPDATED_AT: TableField<CheckoutsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<CheckoutsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CheckoutsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CheckoutsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.checkouts</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.checkouts</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.checkouts</code> table reference
     */
    constructor(): this(DSL.name("checkouts"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutsRecord>?, parentPath: InverseForeignKey<out Record, CheckoutsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CHECKOUTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CheckoutsPath : Checkouts, Path<CheckoutsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutsRecord>?, parentPath: InverseForeignKey<out Record, CheckoutsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CheckoutsRecord>): super(alias, aliased)
        override fun `as`(alias: String): CheckoutsPath = CheckoutsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CheckoutsPath = CheckoutsPath(alias, this)
        override fun `as`(alias: Table<*>): CheckoutsPath = CheckoutsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CheckoutsRecord> = CHECKOUTS_PKEY

    private lateinit var _checkoutLineItems: CheckoutLineItemsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.checkout_line_items</code> table
     */
    fun checkoutLineItems(): CheckoutLineItemsPath {
        if (!this::_checkoutLineItems.isInitialized)
            _checkoutLineItems = CheckoutLineItemsPath(this, null, CHECKOUT_LINE_ITEMS__FK_CHECKOUT_LINE_ITEMS_CHECKOUT.inverseKey)

        return _checkoutLineItems;
    }

    val checkoutLineItems: CheckoutLineItemsPath
        get(): CheckoutLineItemsPath = checkoutLineItems()

    private lateinit var _checkoutPaymentHandlers: CheckoutPaymentHandlersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.checkout_payment_handlers</code> table
     */
    fun checkoutPaymentHandlers(): CheckoutPaymentHandlersPath {
        if (!this::_checkoutPaymentHandlers.isInitialized)
            _checkoutPaymentHandlers = CheckoutPaymentHandlersPath(this, null, CHECKOUT_PAYMENT_HANDLERS__FK_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT.inverseKey)

        return _checkoutPaymentHandlers;
    }

    val checkoutPaymentHandlers: CheckoutPaymentHandlersPath
        get(): CheckoutPaymentHandlersPath = checkoutPaymentHandlers()
    override fun `as`(alias: String): Checkouts = Checkouts(DSL.name(alias), this)
    override fun `as`(alias: Name): Checkouts = Checkouts(alias, this)
    override fun `as`(alias: Table<*>): Checkouts = Checkouts(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Checkouts = Checkouts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Checkouts = Checkouts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Checkouts = Checkouts(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Checkouts = Checkouts(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Checkouts = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Checkouts = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Checkouts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Checkouts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Checkouts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Checkouts = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Checkouts = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Checkouts = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Checkouts = where(DSL.notExists(select))
}
