/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.indexes.IDX_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT_ID
import com.nextmall.jooq.keys.CHECKOUT_PAYMENT_HANDLERS_PKEY
import com.nextmall.jooq.keys.CHECKOUT_PAYMENT_HANDLERS__FK_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT
import com.nextmall.jooq.tables.Checkouts.CheckoutsPath
import com.nextmall.jooq.tables.records.CheckoutPaymentHandlersRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CheckoutPaymentHandlers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CheckoutPaymentHandlersRecord>?,
    parentPath: InverseForeignKey<out Record, CheckoutPaymentHandlersRecord>?,
    aliased: Table<CheckoutPaymentHandlersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CheckoutPaymentHandlersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.checkout_payment_handlers</code>
         */
        val CHECKOUT_PAYMENT_HANDLERS: CheckoutPaymentHandlers = CheckoutPaymentHandlers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CheckoutPaymentHandlersRecord> = CheckoutPaymentHandlersRecord::class.java

    /**
     * The column <code>public.checkout_payment_handlers.id</code>.
     */
    val ID: TableField<CheckoutPaymentHandlersRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.checkout_payment_handlers.checkout_id</code>.
     */
    val CHECKOUT_ID: TableField<CheckoutPaymentHandlersRecord, String?> = createField(DSL.name("checkout_id"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.checkout_payment_handlers.handler_type</code>.
     */
    val HANDLER_TYPE: TableField<CheckoutPaymentHandlersRecord, String?> = createField(DSL.name("handler_type"), SQLDataType.VARCHAR(32).nullable(false), this, "")

    /**
     * The column
     * <code>public.checkout_payment_handlers.handler_provider</code>.
     */
    val HANDLER_PROVIDER: TableField<CheckoutPaymentHandlersRecord, String?> = createField(DSL.name("handler_provider"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.checkout_payment_handlers.sort_order</code>.
     */
    val SORT_ORDER: TableField<CheckoutPaymentHandlersRecord, Int?> = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CheckoutPaymentHandlersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CheckoutPaymentHandlersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CheckoutPaymentHandlersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.checkout_payment_handlers</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.checkout_payment_handlers</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.checkout_payment_handlers</code> table reference
     */
    constructor(): this(DSL.name("checkout_payment_handlers"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutPaymentHandlersRecord>?, parentPath: InverseForeignKey<out Record, CheckoutPaymentHandlersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CHECKOUT_PAYMENT_HANDLERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CheckoutPaymentHandlersPath : CheckoutPaymentHandlers, Path<CheckoutPaymentHandlersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CheckoutPaymentHandlersRecord>?, parentPath: InverseForeignKey<out Record, CheckoutPaymentHandlersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CheckoutPaymentHandlersRecord>): super(alias, aliased)
        override fun `as`(alias: String): CheckoutPaymentHandlersPath = CheckoutPaymentHandlersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CheckoutPaymentHandlersPath = CheckoutPaymentHandlersPath(alias, this)
        override fun `as`(alias: Table<*>): CheckoutPaymentHandlersPath = CheckoutPaymentHandlersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT_ID)
    override fun getPrimaryKey(): UniqueKey<CheckoutPaymentHandlersRecord> = CHECKOUT_PAYMENT_HANDLERS_PKEY
    override fun getReferences(): List<ForeignKey<CheckoutPaymentHandlersRecord, *>> = listOf(CHECKOUT_PAYMENT_HANDLERS__FK_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT)

    /**
     * Get the implicit join path to the <code>public.checkouts</code> table.
     */
    fun checkouts(): CheckoutsPath = checkouts
    val checkouts: CheckoutsPath by lazy { CheckoutsPath(this, CHECKOUT_PAYMENT_HANDLERS__FK_CHECKOUT_PAYMENT_HANDLERS_CHECKOUT, null) }
    override fun `as`(alias: String): CheckoutPaymentHandlers = CheckoutPaymentHandlers(DSL.name(alias), this)
    override fun `as`(alias: Name): CheckoutPaymentHandlers = CheckoutPaymentHandlers(alias, this)
    override fun `as`(alias: Table<*>): CheckoutPaymentHandlers = CheckoutPaymentHandlers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CheckoutPaymentHandlers = CheckoutPaymentHandlers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CheckoutPaymentHandlers = CheckoutPaymentHandlers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CheckoutPaymentHandlers = CheckoutPaymentHandlers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CheckoutPaymentHandlers = CheckoutPaymentHandlers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CheckoutPaymentHandlers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CheckoutPaymentHandlers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CheckoutPaymentHandlers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CheckoutPaymentHandlers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CheckoutPaymentHandlers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CheckoutPaymentHandlers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CheckoutPaymentHandlers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CheckoutPaymentHandlers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CheckoutPaymentHandlers = where(DSL.notExists(select))
}
