/*
 * This file is generated by jOOQ.
 */
package com.nextmall.jooq.tables


import com.nextmall.jooq.Public
import com.nextmall.jooq.indexes.IDX_PRODUCTS_SELLER_ID
import com.nextmall.jooq.keys.PRODUCTS_PKEY
import com.nextmall.jooq.tables.records.ProductsRecord

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Products(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProductsRecord>?,
    parentPath: InverseForeignKey<out Record, ProductsRecord>?,
    aliased: Table<ProductsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProductsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.products</code>
         */
        val PRODUCTS: Products = Products()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProductsRecord> = ProductsRecord::class.java

    /**
     * The column <code>public.products.product_id</code>.
     */
    val PRODUCT_ID: TableField<ProductsRecord, Long?> = createField(DSL.name("product_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.products.name</code>.
     */
    val NAME: TableField<ProductsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.products.price</code>.
     */
    val PRICE: TableField<ProductsRecord, BigDecimal?> = createField(DSL.name("price"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "")

    /**
     * The column <code>public.products.stock</code>.
     */
    val STOCK: TableField<ProductsRecord, Int?> = createField(DSL.name("stock"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.products.seller_id</code>.
     */
    val SELLER_ID: TableField<ProductsRecord, Long?> = createField(DSL.name("seller_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.products.category</code>.
     */
    val CATEGORY: TableField<ProductsRecord, String?> = createField(DSL.name("category"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.products.created_at</code>.
     */
    val CREATED_AT: TableField<ProductsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.products.updated_at</code>.
     */
    val UPDATED_AT: TableField<ProductsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<ProductsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProductsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProductsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.products</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.products</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.products</code> table reference
     */
    constructor(): this(DSL.name("products"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_PRODUCTS_SELLER_ID)
    override fun getPrimaryKey(): UniqueKey<ProductsRecord> = PRODUCTS_PKEY
    override fun getChecks(): List<Check<ProductsRecord>> = listOf(
        Internal.createCheck(this, DSL.name("chk_products_price_positive"), "((price > (0)::numeric))", true),
        Internal.createCheck(this, DSL.name("chk_products_stock_non_negative"), "((stock >= 0))", true)
    )
    override fun `as`(alias: String): Products = Products(DSL.name(alias), this)
    override fun `as`(alias: Name): Products = Products(alias, this)
    override fun `as`(alias: Table<*>): Products = Products(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Products = Products(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Products = Products(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Products = Products(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Products = Products(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Products = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Products = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Products = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Products = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Products = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Products = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Products = where(DSL.notExists(select))
}
