spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  test:
    webtestclient:
      timeout: 30s

kafka:
  enabled: false

nextmall:
  kafka:
    bootstrap-servers: localhost:9092
